"""initial

Revision ID: 146cc611c12e
Revises: 
Create Date: 2026-04-08 14:35:51.666258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '146cc611c12e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observation_cache',
    sa.Column('guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_obs_guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('org_guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('concept_guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('concept_name', sa.String(length=256), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('guid'),
    sa.UniqueConstraint('source_obs_guid')
    )
    with op.batch_alter_table('observation_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observation_cache_concept_guid'), ['concept_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_cache_org_guid'), ['org_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_cache_patient_guid'), ['patient_guid'], unique=False)

    op.create_table('users',
    sa.Column('guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_su', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('guid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('org_memberships',
    sa.Column('guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('org_guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_guid'], ['users.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_table('refresh_log',
    sa.Column('guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('org_guid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rows_fetched', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_guid'], ['users.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_log')
    op.drop_table('org_memberships')
    op.drop_table('users')
    with op.batch_alter_table('observation_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observation_cache_patient_guid'))
        batch_op.drop_index(batch_op.f('ix_observation_cache_org_guid'))
        batch_op.drop_index(batch_op.f('ix_observation_cache_concept_guid'))

    op.drop_table('observation_cache')
    # ### end Alembic commands ###
